### ISSUE TITLE
How to change the volume of the emote music or make it higher?

### ISSUE THREAD

**Issue by KaitoXion** [ToastedOven/BadAssEmotes#1]
Hi,

Is not a bug but I did like to make the Emote music volume as high as in 1.7.1 vers of the mod.
Something like " <volume> 1.00 </volume> for music mod file.

Currently the volume for the emote is kind of too soft for me.

I know that this may be a special unique case, and not many will bother about it.
So i'm writing this to see if there may be alternative setting something in config file of the mod.

**Comment by ToastedOven** [comment]
Yeah I've gotten a few reports about this, I changed the way audio is loaded in the most recent update and for some reason it also lowered it. Not really sure the cause but I haven't had too much time to look at it. I'll probably get to it either tonight or tomorrow

**Comment by ToastedOven** [comment]
I pushed an update changing the audio levels, for some reason only a select few of the bnk files were being read at a lower volume. we boosted the levels of the problem children
