### ISSUE TITLE
Configs to change keybinds

### ISSUE THREAD

**Issue by RetroPrevails** [ToastedOven/BadAssEmotes#2]
Please add a way to change keybinds, for wheel and random emote

**Comment by ToastedOven** [comment]
There are already
![Risk_of_Rain_2_rOUH2PKSxC](https://github.com/ToastedOven/BadAssEmotes/assets/49164897/9c8a7972-8a25-4fb9-9022-499e4f74e9e3)

**Comment by RetroPrevails** [comment]
My fault og, I thought this was the lethal company mod.

**Comment by ToastedOven** [comment]
that mod also has options for that in the settings menu where normal keybinds are located. Everything badasscompany/emotesapi related is prefaced with CustomEmotesAPI 
![Lethal_Company_zCpOTV8Dox](https://github.com/ToastedOven/BadAssEmotes/assets/49164897/60d9e5ff-179d-4ae5-8435-65adcc534038)
